### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [Juza85/intro-data-capstone-musclehub#5]
(Meets Expectations)

Well done on this project! Good job on the data visualizations - the custom colors you used was a nice touch! In addition, your presentation slides were organized and efficient in presenting your findings!

Overall great work on the qualitative and quantitative analyses as well. There is just one small issue to double check on regarding the 3rd significance test (#3).

And as a further challenge, continue exploring these datasets and see if you could ask some more research questions about it. Try designing your own tests and continue to play around with different ways of data visualizations. Have fun!

**Comment by Juza85** [comment]
Thanks @cyouh95 for your review. I'll continue to work with the data and learn from this feedback to make my coding better. Have a nice day and catch you later!
